### ISSUE TITLE
consider supporting ESP32-S3

### ISSUE THREAD

**Issue by gretel** [VladimirP1/esp-gyrologger#14]
nifty new devices coming like https://shop.m5stack.com/products/atoms3-dev-kit-w-0-85-inch-screen - regards

**Comment by B-nutze-RR** [comment]
I'm currently talking to them in order to figure out if we get C3, bmi270, SDcard, button and LED into one product 🤞

**Comment by cedricchangy** [comment]
> I'm currently talking to them in order to figure out if we get C3, bmi270, SDcard, button and LED into one product 🤞

that could be awsome! Do you have any news ?

**Comment by VladimirP1** [comment]
esp32-s3 support added in https://github.com/VladimirP1/esp-gyrologger/commit/f9b571b87c2600c277576ac3dd148fb833da66d2

**Comment by AdrianEddy** [comment]
Pin config for this AtomS3 device:
SDA: 38
SCL: 39
Button: 41

**Comment by pouletmou** [comment]
Hello,
would that be possible to display the filename in use when recording on this device ? I believe you did it with the esp oled screen and the m5stick c plus. I usually film on my canon R6II, and I'm often confused about what file goes with my video rush. I thought that if I could have the name when recording I could say it loud and it would be on my video file.

**Comment by VladimirP1** [comment]
Yes, that is possible to implement, the display is almost the same, but I do not like the way I have done it for m5stickc. I'll think about it

**Comment by pouletmou** [comment]
thank you !

**Comment by DinhLe1984** [comment]
Thank you so much for your great support on this topic:
Now I can get the data file, but the LED signal for recording and stopping does not work on my Atom S3.
@AdrianEddy and @VladimirP1, could you advise me which LED pin in Atoms3 I should set?

**Comment by VladimirP1** [comment]
@DinhLe1984 there's no led on atoms3, but there's a special firmware here https://github.com/VladimirP1/esp-gyrologger/releases/download/v1.1/esplog_esp32s3_atoms3_st7789.zip that abuses the display as a led if you set "display type" to 4 in settings

**Comment by FrankMan1-A** [comment]
Will you ever add support for the M5StickS3 (ESP32S3)?
