### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by igorbmn** [VladimirP1/esp-gyrologger#25]
When i try to flash the firmware, i get this error: 

A fatal error occurred: Failed to connect to Espressif device: No serial data received.

**Comment by igorbmn** [comment]
I was able to flash the firmware and connect to the wifi signal but i don't know how to do this step: 

Go to http://192.168.4.1/settings, enter the SDA and SCL pin numbers you have connected the IMU to, click "Apply".

I'm using a simple usb cable connected to my computer.

**Comment by VladimirP1** [comment]
You do not know the pin numbers? Or what is your problem with this exactly?

**Comment by igorbmn** [comment]
Thank you for the support. I just used a regular usb c cable, didn't mod it. I don't know the pin numbers. I'm using a regular cable via the USB input o my atom s3.

**Comment by VladimirP1** [comment]
https://github.com/VladimirP1/esp-gyrologger/issues/14#issuecomment-1552180153

**Comment by igorbmn** [comment]
It worked, thank you very much, my friend!
