### ISSUE TITLE
Working

### ISSUE THREAD

**Issue by igorbmn** [VladimirP1/esp-gyrologger#26]
Hello, I was able to make it work but I saw a video of a guy using it and his atom s3 blinks green when turned on, and blinks red when recording. How can I do that with mine?

**Comment by VladimirP1** [comment]
Use firmware from `esplog_esp32s3_atoms3_st7789.zip` (if not already) and set in settings "Display type" to 4.

**Comment by igorbmn** [comment]
Do I need to uninstall the the other firmware before flashing this one?

**Comment by VladimirP1** [comment]
No, but if you have problems you can do `esptool erase_flash`

**Comment by igorbmn** [comment]
It works, thank you again. 

One last thing: how do I calibrate it? 

Sorry to ask so many questions, I newby to this world.

**Comment by VladimirP1** [comment]
There is gyro calibration (you just press the green round button on the webpage while the device is stationary). It is saved to flash.
Also there is accel calibration. This is how to do it https://youtu.be/X76fzDprrrg?si=z-T7vP07ozyeVk4C

**Comment by igorbmn** [comment]
Thank you!
