### ISSUE TITLE
control rgb led?

### ISSUE THREAD

**Issue by gretel** [VladimirP1/esp-gyrologger#3]
the [m5stamp](https://shop.m5stack.com/products/m5stamp-c3u-mate-with-pin-headers) boards have a `SK6812` led - the form factor is pretty great for the logging application. am not good with `c++`.. found a library at least: https://github.com/UncleRus/esp-idf-lib/tree/4ca15c4a1495a65def31ed83ef905fba67dde18f/components/led_strip 😄

**Comment by VladimirP1** [comment]
Ordered some ws2812b, will see if this works

**Comment by VladimirP1** [comment]
Here's the official esp-idf example code for ws2912 https://github.com/espressif/esp-idf/tree/master/examples/peripherals/rmt/led_strip

**Comment by gretel** [comment]
@B-nutze-RR i'm trying to have a segment of https://de.aliexpress.com/item/4000154483882.html in the meantime - it's 5V and bright.

**Comment by VladimirP1** [comment]
![vid](https://user-images.githubusercontent.com/10977352/182788822-05f2d701-ec39-43c9-9daf-87a2f4943468.gif)

**Comment by VladimirP1** [comment]
code is in master

**Comment by gretel** [comment]
> code is in master

awesome!

**Comment by B-nutze-RR** [comment]
Very Nice 💪

**Comment by gretel** [comment]
looks and works great using a [`m5stamp c3u`](https://docs.m5stack.com/en/core/stamp_c3u), pins are as shown:

![Screenshot 2022-08-04 at 20 28 26](https://user-images.githubusercontent.com/80815/182925913-0db1af78-9db4-44ad-a90e-3a7b2caf2099.png)
