### ISSUE TITLE
Add lensprofile fields to log file

### ISSUE THREAD

**Issue by mmstac** [VladimirP1/esp-gyrologger#8]
Adding _vendor/lensprofile_ fields to gcsv would allow gyroflow to automatically select the lens profile. Maybe these could be user specified in settings page.

**Comment by VladimirP1** [comment]
Done
Now there is a setting `Extra lines for header`.
You can write there something like `"vendor:potcam","lens_info:wide"`.
The quotes and commas are mandatory.
Also make sure to reload the download page after changing this setting.

**Comment by VladimirP1** [comment]
oh, I broke the settings page...

**Comment by VladimirP1** [comment]
okay, fixed

**Comment by mmstac** [comment]
Thank you, so fast!! Tested and working nicely. One minor note for you next update, the setting example you used : but correct separator needs to be ,
